import pytest
from fastapi.testclient import TestClient

from backend.config import Settings
from backend.main import create_app
from backend.services.chat_adapter import load_chat_service
from backend.services.featherless_client import FeatherlessClient
from backend.services.llm import answer_chat


@pytest.fixture
def client(payload, write_snapshot):
    settings = Settings("mock", write_snapshot(payload))
    with TestClient(create_app(settings, chat_service=answer_chat)) as test_client:
        yield test_client


@pytest.mark.parametrize(
    ("question", "expected"),
    [
        ("Why is idle interactive capacity recoverable?", "4–10 GPU-hours"),
        ("What could go wrong if we enforce an idle timeout?", "$0–$5"),
        ("What evidence supports this recommendation?", "only 1 stored finding"),
    ],
)
def test_idle_interactive_presets_are_grounded(client, question, expected):
    response = client.post(
        "/api/chat",
        json={"question": question, "opportunity_id": "idle-interactive"},
    )

    assert response.status_code == 200
    body = response.json()
    assert expected in body["answer"]
    assert body["confidence"] == 0.7
    assert body["finding_ids"] == ["synthetic-idle-123"]
    assert body["job_ids"] == [123]
    assert body["evidence"][0]["job_id"] == 123
    assert any("synthetic" in caveat.lower() for caveat in body["caveats"])


def test_idle_interactive_answer_does_not_claim_verified_savings(client):
    response = client.post(
        "/api/chat",
        json={
            "question": "Why is idle interactive capacity recoverable?",
            "opportunity_id": "idle-interactive",
        },
    )

    answer = response.json()["answer"]
    assert "not guaranteed savings" in answer
    assert "Low utilization alone is not proof of waste" in answer


def test_answer_chat_is_loadable_from_compose_configuration():
    assert load_chat_service("backend.services.llm:answer_chat") is answer_chat


def test_greeting_does_not_become_a_recoverability_claim(client):
    response = client.post(
        "/api/chat",
        json={"question": "hello", "opportunity_id": "idle-interactive"},
    )

    body = response.json()
    assert body["answer"].startswith("Hello!")
    assert "may be recoverable" not in body["answer"]
    assert body["confidence"] is None
    assert body["evidence"] == []
    assert body["finding_ids"] == []
    assert body["job_ids"] == []


def test_capability_question_has_no_analytical_claims(client):
    response = client.post(
        "/api/chat",
        json={
            "question": "what can you do",
            "opportunity_id": "idle-interactive",
        },
    )

    body = response.json()
    assert body["answer"].startswith("I can answer general questions")
    assert "Pilot a warning" not in body["answer"]
    assert body["confidence"] is None
    assert body["evidence"] == []
    assert body["finding_ids"] == []
    assert body["job_ids"] == []


def test_featherless_wording_preserves_authoritative_citations(
    client, monkeypatch
):
    monkeypatch.setenv("FEATHERLESS_API_KEY", "test-key-not-real")

    async def generated(self, *, system_prompt, user_prompt):
        assert "Never invent" in system_prompt
        assert "synthetic-idle-123" in user_prompt
        return {
            "answer": "Investigate the stored 4–10 GPU-hours range; it is not guaranteed savings.",
            "risk": "Useful interactive work could be interrupted.",
            "recommendation": "Pilot a warning and idle timeout with an opt-out.",
            "gpu_related": True,
        }

    monkeypatch.setattr(FeatherlessClient, "generate_json", generated)
    response = client.post(
        "/api/chat",
        json={
            "question": "Why is this recoverable?",
            "opportunity_id": "idle-interactive",
        },
    )

    body = response.json()
    assert body["answer"].startswith("Investigate the stored 4–10 GPU-hours")
    assert body["finding_ids"] == ["synthetic-idle-123"]
    assert body["job_ids"] == [123]
    assert any("generated by Featherless" in caveat for caveat in body["caveats"])


def test_general_question_does_not_send_gpu_context(client, monkeypatch):
    monkeypatch.setenv("FEATHERLESS_API_KEY", "test-key-not-real")

    async def generated(self, *, system_prompt, user_prompt):
        assert "what this project can do" in system_prompt
        assert "synthetic-idle-123" not in user_prompt
        assert "opportunity" not in user_prompt
        return {
            "answer": "I can answer general questions and explain the dashboard when asked.",
            "risk": "Not applicable",
            "recommendation": "Ask me a question.",
            "gpu_related": True,
        }

    monkeypatch.setattr(FeatherlessClient, "generate_json", generated)
    response = client.post(
        "/api/chat",
        json={
            "question": "Hi, what can you do?",
            "opportunity_id": "idle-interactive",
        },
    )

    body = response.json()
    assert body["answer"].startswith("I can answer general questions")
    assert body["confidence"] is None
    assert body["evidence"] == []
    assert body["finding_ids"] == []
    assert body["job_ids"] == []


def test_unsupported_featherless_number_uses_grounded_fallback(client, monkeypatch):
    monkeypatch.setenv("FEATHERLESS_API_KEY", "test-key-not-real")

    async def ungrounded(self, **kwargs):
        return {
            "answer": "This saves $999.",
            "risk": "No risk.",
            "recommendation": "Apply immediately.",
            "gpu_related": True,
        }

    monkeypatch.setattr(FeatherlessClient, "generate_json", ungrounded)
    response = client.post(
        "/api/chat",
        json={
            "question": "Why is this recoverable?",
            "opportunity_id": "idle-interactive",
        },
    )

    body = response.json()
    assert "$999" not in body["answer"]
    assert "not guaranteed savings" in body["answer"]
    assert any("ungrounded response" in caveat for caveat in body["caveats"])


def test_unrelated_question_uses_safe_fallback_without_provider(client):
    response = client.post(
        "/api/chat",
        json={
            "question": "What is the weather today?",
            "opportunity_id": "idle-interactive",
        },
    )

    body = response.json()
    assert "LLM provider is unavailable" in body["answer"]
    assert "may be recoverable" not in body["answer"]
    assert body["confidence"] is None
    assert body["evidence"] == []
    assert body["finding_ids"] == []
    assert body["job_ids"] == []
